// Command flexkb is the CLI for the flexkb modular xkb generator.
//
// Subcommands:
//
//	compose <layout-file> <variant>      print one variant to stdout
//	generate <out-dir>                   write all layouts to <out-dir>/symbols/
//	build <out-dir> [--xkb=/path]        generate modular + fallback-copy rest
//	verify <layout-file> <variant>       compose then compare against system xkb
//	list                                 list known modular layouts
//	paths                                show which data directories are active
//	activate <file> <variant>            generate into ~/.xkb and setxkbmap to it
package main

import (
	"fmt"
	"io"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strings"

	"github.com/lapingvino/flexkb/internal/bulkconvert"
	"github.com/lapingvino/flexkb/internal/compose"
	"github.com/lapingvino/flexkb/internal/composewriter"
	"github.com/lapingvino/flexkb/internal/dropincheck"
	"github.com/lapingvino/flexkb/internal/model"
	"github.com/lapingvino/flexkb/internal/rulespatch"
	"github.com/lapingvino/flexkb/internal/validate"
	"github.com/lapingvino/flexkb/internal/xkbparser"
	"github.com/lapingvino/flexkb/internal/xkbwriter"
)

// loadComposeChains resolves the LayoutSpec's Compose names against
// the data root. Missing chains are skipped with a warning (so a
// half-authored layout doesn't crash the build); each successfully
// loaded chain is returned in the order listed.
func loadComposeChains(root model.DataRoot, v model.LayoutSpec) ([]model.ComposeChain, error) {
	if len(v.Compose) == 0 {
		return nil, nil
	}
	chains := make([]model.ComposeChain, 0, len(v.Compose))
	for _, name := range v.Compose {
		c, err := root.Compose(name)
		if err != nil {
			fmt.Fprintf(os.Stderr, "warn: compose chain %q referenced by %q not found: %v\n", name, v.Name, err)
			continue
		}
		chains = append(chains, c)
	}
	return chains, nil
}

// writeVariantCompose emits the X-Compose snippet for one variant's
// listed chains. Returns false if the variant has no chains (caller
// can skip the file write).
func writeVariantCompose(w io.Writer, root model.DataRoot, lf model.LayoutFile, v model.LayoutSpec) (bool, error) {
	chains, err := loadComposeChains(root, v)
	if err != nil {
		return false, err
	}
	if len(chains) == 0 {
		return false, nil
	}
	hdr := fmt.Sprintf("Generated by flexkb for %s(%s). Source: data/compose/*.yaml.\nMerge into ~/.XCompose to enable these sequences for X11/Wayland clients\nthat read the system Compose configuration (libX11, libxkbcommon).", lf.File, v.Name)
	return true, composewriter.WriteFile(w, composewriter.Options{HeaderComment: hdr}, chains)
}

const defaultXKBRoot = "/usr/share/X11/xkb"

func main() {
	if len(os.Args) < 2 {
		usage()
		os.Exit(2)
	}
	cmd := os.Args[1]
	args := os.Args[2:]

	switch cmd {
	case "compose":
		runCompose(args)
	case "generate":
		runGenerate(args)
	case "build":
		runBuild(args)
	case "verify":
		runVerify(args)
	case "list":
		runList(args)
	case "paths":
		runPaths(args)
	case "activate":
		runActivate(args)
	case "info":
		runInfo(args)
	case "validate":
		runValidate(args)
	case "doctor":
		runDoctor(args)
	case "migrate-suggest":
		runMigrateSuggest(args)
	case "dropin-check":
		runDropinCheck(args)
	case "serve":
		runServe(args)
	case "gui":
		runGui(args)
	case "-h", "--help", "help":
		usage()
	default:
		fmt.Fprintf(os.Stderr, "unknown command %q\n", cmd)
		usage()
		os.Exit(2)
	}
}

func usage() {
	fmt.Fprintln(os.Stderr, `flexkb — modular xkb layout generator

Usage:
  flexkb compose [--data DIR] <layout-file> <variant>
  flexkb generate [--data DIR] <output-dir>
  flexkb build [--data DIR] [--xkb /usr/share/X11/xkb] <output-dir>
  flexkb verify [--data DIR] [--xkb /usr/share/X11/xkb] <layout-file> <variant>
  flexkb list [--data DIR]
  flexkb paths
  flexkb activate <layout-file> <variant>
  flexkb serve [--data DIR] [--addr host:port] [--open]
  flexkb gui   [--data DIR] [--addr host:port] [--engine NAME]

Commands:
  compose   Emit one variant to stdout (debug / preview).
  generate  Write all modular layouts to <output-dir>/symbols/.
  build     generate, then copy any remaining xkb tree from --xkb verbatim,
            so output is a complete drop-in /usr/share/X11/xkb replacement.
  verify    Compose a variant and compare key-by-key against the same-named
            variant in <xkb>/symbols/<layout-file>.
  list      Print the layout-file / variant matrix flexkb knows about.
  paths     Show the data directories being consulted, in priority order.
            Per-user overrides go in $XDG_CONFIG_HOME/flexkb/data (default
            ~/.config/flexkb/data) and shadow same-named system files.
  activate  Generate the modular tree to ~/.xkb and invoke setxkbmap to
            apply <layout-file>/<variant> in the current X session.
  info      Per-layout report: which variants are modular vs upstream
            passthrough. Pass --xkb to count upstream variants too.
  migrate-  Pattern-match an old xkb variant name like dvorak-intl into a
   suggest  flexkb composition (transformation + additions + substitutions).
            Output is YAML ready to paste into data/layouts/<file>.yaml.
  dropin-   Verify a built xkb tree is a strict superset of an upstream
   check    one. Fails (exit 1) if any file, xkb_symbols block, or rules
            registry layout/variant from upstream is missing in built.
            Called by the PKGBUILD check() to enforce drop-in compat.
  serve     Start an HTTP server (default localhost:7878) with a live
            preview UI. Pick a layout/variant in the browser, see the
            composed key grid color-coded by source dimension
            (transformation/positional overlay/letter overlay/sub).
            --open launches xdg-open on the URL.
  gui       Same server, but wrap it in a dedicated window. Engines:
            webview (native GTK/webkit2gtk, needs -tags webview),
            lorca (Chromium --app= mode, needs -tags lorca),
            browser (xdg-open fallback, always available). --engine=
            picks one, --list-engines shows what's compiled in.
            Used by /usr/share/applications/flexkb.desktop.

--data DIR overrides discovery and uses only DIR. Without it, flexkb walks
the user/system/dev paths in order — see "flexkb paths" for the resolved
list. New YAML files in a user directory just appear in "flexkb list";
same-named files in higher-priority directories shadow lower ones.`)
}

// dataPaths pulls --data / --data=… out of args. If supplied (possibly
// multiple times) the explicit list wins. Otherwise we use the XDG-aware
// discovery order so user overrides under ~/.config/flexkb/data are
// picked up automatically.
func dataPaths(args []string) ([]string, []string) {
	var override []string
	rest := make([]string, 0, len(args))
	for i := 0; i < len(args); i++ {
		a := args[i]
		switch {
		case a == "--data" && i+1 < len(args):
			override = append(override, args[i+1])
			i++
		case strings.HasPrefix(a, "--data="):
			override = append(override, strings.TrimPrefix(a, "--data="))
		default:
			rest = append(rest, a)
		}
	}
	if len(override) > 0 {
		return override, rest
	}
	return model.DiscoverPaths(), rest
}

func makeRoot(paths []string) model.DataRoot {
	if len(paths) == 1 {
		return model.DataRoot{Path: paths[0]}
	}
	return model.DataRoot{Paths: paths}
}

// makeRootFn returns a per-request DataRoot factory. When override is
// true (user passed --data) we freeze the resolved list; otherwise we
// re-discover on every call so saves into ~/.config/flexkb/data/ that
// just brought a new directory into existence show up immediately
// without restarting the server.
func makeRootFn(paths []string, override bool) func() model.DataRoot {
	if override {
		root := makeRoot(paths)
		return func() model.DataRoot { return root }
	}
	return func() model.DataRoot { return makeRoot(model.DiscoverPaths()) }
}

// xkbDir extracts --xkb from args; used by build/verify which both need it.
func xkbDir(args []string) (string, []string) {
	out := defaultXKBRoot
	rest := args[:0]
	for i := 0; i < len(args); i++ {
		a := args[i]
		switch {
		case a == "--xkb" && i+1 < len(args):
			out = args[i+1]
			i++
		case strings.HasPrefix(a, "--xkb="):
			out = strings.TrimPrefix(a, "--xkb=")
		default:
			rest = append(rest, a)
		}
	}
	return out, rest
}

func runCompose(args []string) {
	paths, rest := dataPaths(args)
	// --xcompose switches output from xkb_symbols to the X-Compose
	// snippet that activates the variant's compose chains. Default
	// behaviour stays "print xkb_symbols block" for backwards-compat.
	xcomposeMode := false
	filtered := rest[:0]
	for _, a := range rest {
		if a == "--xcompose" {
			xcomposeMode = true
			continue
		}
		filtered = append(filtered, a)
	}
	rest = filtered
	if len(rest) != 2 {
		fmt.Fprintln(os.Stderr, "usage: flexkb compose [--xcompose] <layout-file> <variant>")
		os.Exit(2)
	}
	root := makeRoot(paths)
	lf, err := root.LayoutFile(rest[0])
	check(err)
	for _, v := range lf.Variants {
		if v.Name != rest[1] {
			continue
		}
		if xcomposeMode {
			emitted, err := writeVariantCompose(os.Stdout, root, lf, v)
			check(err)
			if !emitted {
				fmt.Fprintf(os.Stderr, "%s(%s) has no compose chains configured\n", rest[0], rest[1])
				os.Exit(1)
			}
			return
		}
		res, err := compose.Compose(root, v)
		check(err)
		for _, w := range res.Warnings {
			fmt.Fprintln(os.Stderr, "warn:", w)
		}
		check(xkbwriter.WriteVariant(os.Stdout, xkbwriter.Options{}, res.Layout))
		return
	}
	fmt.Fprintf(os.Stderr, "variant %q not found in %s\n", rest[1], rest[0])
	os.Exit(1)
}

func runGenerate(args []string) {
	paths, rest := dataPaths(args)
	if len(rest) != 1 {
		fmt.Fprintln(os.Stderr, "usage: flexkb generate <output-dir>")
		os.Exit(2)
	}
	out := rest[0]
	root := makeRoot(paths)
	names, err := root.ListLayoutFiles()
	check(err)
	symbolsDir := filepath.Join(out, "symbols")
	check(os.MkdirAll(symbolsDir, 0o755))
	for _, name := range names {
		if err := generateOne(root, name, symbolsDir); err != nil {
			fmt.Fprintf(os.Stderr, "generating %s: %v\n", name, err)
			os.Exit(1)
		}
	}
	fmt.Printf("wrote %d layout file(s) to %s\n", len(names), symbolsDir)
	composeCount, err := generateComposeFiles(root, names, out)
	check(err)
	if composeCount > 0 {
		fmt.Printf("wrote %d compose chain file(s) to %s\n", composeCount, filepath.Join(out, "Compose.d"))
	}
}

// generateComposeFiles emits one X-Compose file per (layout, variant)
// that declares `compose:` chains, into <out>/Compose.d/<file>-<variant>.
// Naming mirrors the xkb/<layout>(<variant>) addressing scheme so the
// activate flow can pick the matching file without re-walking the data
// tree. Returns the number of files emitted.
func generateComposeFiles(root model.DataRoot, names []string, outRoot string) (int, error) {
	dir := filepath.Join(outRoot, "Compose.d")
	count := 0
	for _, name := range names {
		lf, err := root.LayoutFile(name)
		if err != nil {
			return count, err
		}
		for _, v := range lf.Variants {
			if len(v.Compose) == 0 {
				continue
			}
			if err := os.MkdirAll(dir, 0o755); err != nil {
				return count, err
			}
			outPath := filepath.Join(dir, fmt.Sprintf("%s-%s", lf.File, v.Name))
			f, err := os.Create(outPath)
			if err != nil {
				return count, err
			}
			emitted, err := writeVariantCompose(f, root, lf, v)
			f.Close()
			if err != nil {
				return count, fmt.Errorf("compose %s(%s): %w", lf.File, v.Name, err)
			}
			if emitted {
				count++
			} else {
				// No chains actually loaded (all references missing);
				// drop the empty file we just created.
				os.Remove(outPath)
			}
		}
	}
	return count, nil
}

func generateOne(root model.DataRoot, name, symbolsDir string) error {
	return generateOneWithUpstream(root, name, symbolsDir, "")
}

// generateOneWithUpstream composes our modular variants and, when an
// upstream xkb tree is available, also passes through every upstream
// variant we don't explicitly own. This is what makes the build "drop-in"
// — a user mid-session on us(dvorak-intl) doesn't lose their layout just
// because flexkb hasn't decomposed dvorak-intl into a modular form yet.
func generateOneWithUpstream(root model.DataRoot, name, symbolsDir, upstreamRoot string) error {
	lf, err := root.LayoutFile(name)
	if err != nil {
		return err
	}

	// Load upstream variants if we have a reference tree.
	var upstreamVariants []xkbparser.Variant
	upstreamByName := map[string]xkbparser.Variant{}
	if upstreamRoot != "" {
		b, err := os.ReadFile(filepath.Join(upstreamRoot, "symbols", lf.File))
		if err == nil {
			parsed, err := xkbparser.Parse(string(b))
			if err == nil {
				upstreamVariants = parsed.Variants
				for _, v := range parsed.Variants {
					upstreamByName[v.Name] = v
				}
			}
		}
	}

	// Compose what we own modularly. Variants marked Passthrough resolve
	// against upstream raw source instead.
	var composed []model.ComposedLayout
	var passthroughs []string
	ownedNames := map[string]bool{}
	for _, v := range lf.Variants {
		ownedNames[v.Name] = true
		if v.Passthrough {
			if up, ok := upstreamByName[v.Name]; ok && up.RawSource != "" {
				passthroughs = append(passthroughs, up.RawSource)
			} else {
				fmt.Fprintf(os.Stderr, "warn (%s/%s): marked passthrough but no upstream source available\n", name, v.Name)
			}
			continue
		}
		res, err := compose.Compose(root, v)
		if err != nil {
			return err
		}
		for _, w := range res.Warnings {
			fmt.Fprintf(os.Stderr, "warn (%s/%s): %s\n", name, v.Name, w)
		}
		composed = append(composed, res.Layout)
	}

	// Implicit passthrough: any upstream variant we don't own is included
	// verbatim. The user's existing setxkbmap config keeps working.
	var implicit []string
	for _, up := range upstreamVariants {
		if ownedNames[up.Name] {
			continue
		}
		if up.RawSource == "" {
			continue
		}
		implicit = append(implicit, up.RawSource)
	}

	f, err := os.Create(filepath.Join(symbolsDir, lf.File))
	if err != nil {
		return err
	}
	defer f.Close()

	opts := xkbwriter.Options{HeaderComment: fmt.Sprintf("Generated by flexkb for %q. Modular variants are composed from data/ sources; remaining variants are passed through verbatim from the source xkb tree.", lf.File)}
	if err := xkbwriter.WriteFile(f, opts, composed); err != nil {
		return err
	}
	// Append passthrough raw sources after the composed blocks. The xkb
	// language is order-tolerant for variant blocks within a file.
	for _, raw := range passthroughs {
		if _, err := fmt.Fprintf(f, "\n\n%s\n", raw); err != nil {
			return err
		}
	}
	for _, raw := range implicit {
		if _, err := fmt.Fprintf(f, "\n\n%s\n", raw); err != nil {
			return err
		}
	}
	return nil
}

func runBuild(args []string) {
	paths, rest := dataPaths(args)
	xkb, rest := xkbDir(rest)
	if len(rest) != 1 {
		fmt.Fprintln(os.Stderr, "usage: flexkb build [--xkb /path] <output-dir>")
		os.Exit(2)
	}
	out := rest[0]
	root := makeRoot(paths)

	// Step 1: list which symbols files we own modularly — they'll be skipped
	// by the fallback copy in step 3.
	names, err := root.ListLayoutFiles()
	check(err)
	skip := map[string]bool{}
	for _, n := range names {
		lf, err := root.LayoutFile(n)
		check(err)
		skip[filepath.Join("symbols", lf.File)] = true
	}

	// Step 2: copy the rest of the upstream xkb tree.
	check(bulkconvert.CopyTree(xkb, out, skip))

	// Step 3: write our modular symbols files on top, passing through any
	// upstream variants we don't own so existing user configs keep
	// working.
	symbolsDir := filepath.Join(out, "symbols")
	check(os.MkdirAll(symbolsDir, 0o755))
	for _, n := range names {
		check(generateOneWithUpstream(root, n, symbolsDir, xkb))
	}

	// Step 4: patch the rules registry so GUI keyboard pickers list our
	// variants. Missing rules files are silently skipped.
	infos := []rulespatch.LayoutInfo{}
	for _, n := range names {
		lf, err := root.LayoutFile(n)
		check(err)
		info := rulespatch.LayoutInfo{File: lf.File, Description: lf.File}
		for _, v := range lf.Variants {
			if v.Default && info.Description == lf.File {
				info.Description = v.Description
			}
			info.Variants = append(info.Variants, rulespatch.VariantInfo{
				Name:        v.Name,
				Description: v.Description,
			})
		}
		infos = append(infos, info)
	}
	check(rulespatch.EnsureRules(out, infos))

	fmt.Printf("built complete xkb tree in %s (%d modular layout file(s), rest copied from %s)\n", out, len(names), xkb)
	fmt.Printf("patched rules registry so %d flexkb layout file(s) surface in GUI pickers\n", len(infos))

	// Step 5: emit X-Compose files for variants that declare compose:
	// chains. Lands in <out>/Compose.d/<file>-<variant>; activate copies
	// the matching file to ~/.XCompose when the user picks that variant.
	composeCount, err := generateComposeFiles(root, names, out)
	check(err)
	if composeCount > 0 {
		fmt.Printf("wrote %d compose chain file(s) to %s\n", composeCount, filepath.Join(out, "Compose.d"))
	}
}

func runVerify(args []string) {
	paths, rest := dataPaths(args)
	xkb, rest := xkbDir(rest)
	if len(rest) != 2 {
		fmt.Fprintln(os.Stderr, "usage: flexkb verify [--xkb /path] <layout-file> <variant>")
		os.Exit(2)
	}
	root := makeRoot(paths)
	lf, err := root.LayoutFile(rest[0])
	check(err)

	var spec model.LayoutSpec
	found := false
	for _, v := range lf.Variants {
		if v.Name == rest[1] {
			spec = v
			found = true
			break
		}
	}
	if !found {
		fmt.Fprintf(os.Stderr, "variant %q not found in layout %q\n", rest[1], rest[0])
		os.Exit(1)
	}

	res, err := compose.Compose(root, spec)
	check(err)
	composed := res.Layout

	// Read the reference xkb file.
	refPath := filepath.Join(xkb, "symbols", lf.File)
	refBytes, err := os.ReadFile(refPath)
	check(err)
	parsed, err := xkbparser.Parse(string(refBytes))
	check(err)

	var ref *xkbparser.Variant
	for i := range parsed.Variants {
		if parsed.Variants[i].Name == spec.Name {
			ref = &parsed.Variants[i]
			break
		}
	}
	if ref == nil {
		fmt.Fprintf(os.Stderr, "reference variant %q not found in %s\n", spec.Name, refPath)
		os.Exit(1)
	}

	diffs := compareKeys(composed.Symbols, ref.Symbols)
	if len(diffs) == 0 {
		fmt.Printf("OK: composed %s/%s matches %s\n", lf.File, spec.Name, refPath)
		return
	}
	sort.Strings(diffs)
	fmt.Printf("DIFF: composed %s/%s differs from %s in %d key(s):\n", lf.File, spec.Name, refPath, len(diffs))
	for _, d := range diffs {
		fmt.Println("  ", d)
	}
	os.Exit(1)
}

func compareKeys(a, b map[string]model.KeySymbols) []string {
	var diffs []string
	seen := map[string]bool{}
	for k, av := range a {
		seen[k] = true
		bv, ok := b[k]
		if !ok {
			diffs = append(diffs, fmt.Sprintf("%s: composed=%v reference=<absent>", k, av.Levels))
			continue
		}
		if !sameLevels(av.Levels, bv.Levels) {
			diffs = append(diffs, fmt.Sprintf("%s: composed=%v reference=%v", k, av.Levels, bv.Levels))
		}
	}
	for k, bv := range b {
		if seen[k] {
			continue
		}
		diffs = append(diffs, fmt.Sprintf("%s: composed=<absent> reference=%v", k, bv.Levels))
	}
	return diffs
}

func sameLevels(a, b []string) bool {
	// Reference (xkb) often pads to 4 levels with duplicates of level 1 or
	// asciitilde for "do nothing" — we treat trailing-empty / trailing-NoSymbol
	// as equivalent to absence so the comparison isn't drowned in noise.
	a = trimNoise(a)
	b = trimNoise(b)
	if len(a) != len(b) {
		return false
	}
	for i := range a {
		if a[i] != b[i] {
			return false
		}
	}
	return true
}

func trimNoise(a []string) []string {
	out := append([]string(nil), a...)
	for len(out) > 0 {
		last := out[len(out)-1]
		if last == "" || last == "NoSymbol" {
			out = out[:len(out)-1]
			continue
		}
		break
	}
	return out
}

func runList(args []string) {
	paths, _ := dataPaths(args)
	root := makeRoot(paths)
	names, err := root.ListLayoutFiles()
	check(err)
	for _, n := range names {
		lf, err := root.LayoutFile(n)
		if err != nil {
			fmt.Fprintln(os.Stderr, err)
			continue
		}
		for _, v := range lf.Variants {
			adds := strings.Join(v.Additions, "+")
			if adds == "" {
				adds = "-"
			}
			subs := strings.Join(v.Substitutions, "+")
			if subs == "" {
				subs = "-"
			}
			fmt.Printf("%s\t%s\t%s + %s + add:%s + sub:%s\n", lf.File, v.Name, v.Physical, v.Transformation, adds, subs)
		}
	}
}

func runPaths(args []string) {
	paths, rest := dataPaths(args)
	if len(rest) != 0 {
		fmt.Fprintln(os.Stderr, "usage: flexkb paths")
		os.Exit(2)
	}
	fmt.Println("flexkb data search path (highest priority first):")
	if len(paths) == 0 {
		fmt.Println("  (none — set $XDG_CONFIG_HOME/flexkb/data or install the package)")
		return
	}
	for i, p := range paths {
		fmt.Printf("  %d. %s  [%s]\n", i+1, p, classifyPath(p))
	}
	fmt.Println("\nFiles in higher-priority directories shadow same-named files lower\ndown. New files just add to the available set; see `flexkb list`.")
}

// runActivate generates the modular xkb tree into ~/.xkb and invokes
// setxkbmap with -I$HOME/.xkb so the new variant is picked up by the
// running X session. The user-level overrides are honoured because
// `flexkb generate` already walks the layered data root.
func runActivate(args []string) {
	paths, rest := dataPaths(args)
	if len(rest) != 2 {
		fmt.Fprintln(os.Stderr, "usage: flexkb activate <layout-file> <variant>")
		os.Exit(2)
	}
	root := makeRoot(paths)
	layoutName, variantName := rest[0], rest[1]

	// Sanity-check the variant exists before clobbering ~/.xkb.
	lf, err := root.LayoutFile(layoutName)
	check(err)
	found := false
	for _, v := range lf.Variants {
		if v.Name == variantName {
			found = true
			break
		}
	}
	if !found {
		fmt.Fprintf(os.Stderr, "variant %q not found in layout %q\n", variantName, layoutName)
		os.Exit(1)
	}

	home, err := os.UserHomeDir()
	check(err)
	xkbDir := filepath.Join(home, ".xkb")
	symbolsDir := filepath.Join(xkbDir, "symbols")
	check(os.MkdirAll(symbolsDir, 0o755))

	// Regenerate everything so the user-dir tree reflects current sources.
	names, err := root.ListLayoutFiles()
	check(err)
	for _, n := range names {
		check(generateOne(root, n, symbolsDir))
	}
	fmt.Printf("wrote %d layout file(s) to %s\n", len(names), symbolsDir)

	// Install the variant's X-Compose chains to ~/.XCompose if any are
	// declared. If a prior ~/.XCompose exists and we didn't author it,
	// preserve it as ~/.XCompose.flexkb-backup-<timestamp> so the user
	// can restore their hand-written includes after `flexkb activate`.
	var variantSpec model.LayoutSpec
	for _, v := range lf.Variants {
		if v.Name == variantName {
			variantSpec = v
			break
		}
	}
	if len(variantSpec.Compose) > 0 {
		check(installUserXCompose(root, home, lf, variantSpec))
	}

	// Apply via setxkbmap. -I prepends the include path so xkbcomp finds
	// our symbols/<file> before the system one.
	cmd := exec.Command("setxkbmap",
		"-I"+xkbDir,
		"-layout", layoutName,
		"-variant", variantName,
		"-print",
	)
	out, err := cmd.Output()
	if err != nil {
		fmt.Fprintf(os.Stderr, "setxkbmap -print failed: %v\n  (is X running? for Wayland, use xkbcli or your compositor's input config)\n", err)
		os.Exit(1)
	}

	// Pipe the keymap through xkbcomp to actually load it.
	xkbcomp := exec.Command("xkbcomp", "-I"+xkbDir, "-", os.Getenv("DISPLAY"))
	xkbcomp.Stdin = strings.NewReader(string(out))
	xkbcomp.Stderr = os.Stderr
	if err := xkbcomp.Run(); err != nil {
		fmt.Fprintf(os.Stderr, "xkbcomp failed: %v\n", err)
		os.Exit(1)
	}
	fmt.Printf("activated %s(%s) for display %s\n", layoutName, variantName, os.Getenv("DISPLAY"))
	fmt.Println("\nThis applies to the running X session only. Add this command to\nyour login script (e.g. ~/.xsessionrc) to persist across logins.")
}

// installUserXCompose writes the variant's compose chains to
// ~/.XCompose. Any pre-existing ~/.XCompose that wasn't authored by us
// is moved aside to a timestamped backup, so a hand-written file with
// the user's own includes is recoverable. The marker line at the top
// of every flexkb-authored file lets us tell ours apart from theirs.
func installUserXCompose(root model.DataRoot, home string, lf model.LayoutFile, v model.LayoutSpec) error {
	target := filepath.Join(home, ".XCompose")
	if existing, err := os.ReadFile(target); err == nil {
		if !strings.Contains(string(existing[:min(len(existing), 512)]), xcomposeMarker) {
			backup := fmt.Sprintf("%s.flexkb-backup-%d", target, os.Getpid())
			if err := os.Rename(target, backup); err != nil {
				return fmt.Errorf("backup existing ~/.XCompose: %w", err)
			}
			fmt.Fprintf(os.Stderr, "moved pre-existing ~/.XCompose to %s\n", backup)
		}
	}
	f, err := os.Create(target)
	if err != nil {
		return err
	}
	defer f.Close()
	hdr := fmt.Sprintf("%s\nActive variant: %s(%s). Edit data/compose/*.yaml and rerun\n`flexkb activate %s %s` to regenerate. Lines below are an X11/Wayland\nCompose configuration; standard editors and Compose tooling apply.",
		xcomposeMarker, lf.File, v.Name, lf.File, v.Name)
	emitted, err := writeVariantCompose(f, root, lf, v)
	if err != nil {
		return err
	}
	if !emitted {
		// No chains loaded — leave the file empty rather than half-written
		// so we don't shadow whatever IM defaults libX11 would otherwise
		// fall back to.
		f.Truncate(0)
		return nil
	}
	// Re-write with the proper header now that we know there's content
	// (writeVariantCompose already wrote a header — close, truncate,
	// rewrite to merge the two so we don't end up with double headers).
	f.Close()
	f2, err := os.Create(target)
	if err != nil {
		return err
	}
	defer f2.Close()
	_, err = writeVariantComposeWithHeader(f2, root, v, hdr)
	if err != nil {
		return err
	}
	fmt.Printf("wrote ~/.XCompose for %s(%s) — %d chain(s)\n", lf.File, v.Name, len(v.Compose))
	return nil
}

// xcomposeMarker identifies flexkb-authored ~/.XCompose files so we
// don't clobber the user's own without backing it up first.
const xcomposeMarker = "# flexkb-managed XCompose"

// writeVariantComposeWithHeader is the header-customisable version of
// writeVariantCompose, used by installUserXCompose to embed the
// activation context (layout/variant + edit instructions) instead of
// the generic build header.
func writeVariantComposeWithHeader(w io.Writer, root model.DataRoot, v model.LayoutSpec, header string) (bool, error) {
	chains, err := loadComposeChains(root, v)
	if err != nil {
		return false, err
	}
	if len(chains) == 0 {
		return false, nil
	}
	return true, composewriter.WriteFile(w, composewriter.Options{HeaderComment: header}, chains)
}

// runInfo prints a per-layout report: which variants are modular, which
// are explicitly passthrough, and (if --xkb is given) which upstream
// variants will be implicit-passthrough at build time.
func runInfo(args []string) {
	paths, rest := dataPaths(args)
	xkb, rest := xkbDir(rest)
	root := makeRoot(paths)

	names, err := root.ListLayoutFiles()
	check(err)
	if len(rest) == 1 {
		names = []string{rest[0]}
	}

	for _, n := range names {
		lf, err := root.LayoutFile(n)
		if err != nil {
			fmt.Fprintln(os.Stderr, err)
			continue
		}
		owned := map[string]string{} // variant -> kind ("modular" | "passthrough")
		for _, v := range lf.Variants {
			if v.Passthrough {
				owned[v.Name] = "passthrough"
			} else {
				owned[v.Name] = "modular"
			}
		}
		var upstreamVariants []string
		if xkb != "" {
			if b, err := os.ReadFile(filepath.Join(xkb, "symbols", lf.File)); err == nil {
				if parsed, err := xkbparser.Parse(string(b)); err == nil {
					for _, v := range parsed.Variants {
						upstreamVariants = append(upstreamVariants, v.Name)
					}
				}
			}
		}

		modular := 0
		passthrough := 0
		implicit := 0
		for _, k := range owned {
			switch k {
			case "modular":
				modular++
			case "passthrough":
				passthrough++
			}
		}
		for _, name := range upstreamVariants {
			if _, ok := owned[name]; !ok {
				implicit++
			}
		}

		fmt.Printf("%s: %d modular, %d explicit passthrough, %d implicit passthrough from xkb\n",
			lf.File, modular, passthrough, implicit)
		for _, v := range lf.Variants {
			kind := "modular"
			if v.Passthrough {
				kind = "passthrough"
			}
			fmt.Printf("  %-30s [%s]\n", v.Name, kind)
		}
		if xkb != "" {
			for _, name := range upstreamVariants {
				if _, ok := owned[name]; ok {
					continue
				}
				fmt.Printf("  %-30s [implicit-passthrough]\n", name)
			}
		}
	}
}

// runMigrateSuggest takes an old-style xkb variant name like
// `dvorak-intl` or `phonetic_winkeys` and emits a flexkb composition
// guess. Pure heuristic — token-match against known transformations,
// additions, substitutions — but covers the common cases and gives the
// user a starting point to drop into their layouts/ file.
// runValidate walks a variant's full layer stack, compares the
// produced character set against the target locale's required set,
// and reports any gaps plus which OTHER layers in data/ would
// supply each missing character. The actionable form of "are my
// composition choices right for what I'm trying to type?"
func runValidate(args []string) {
	paths, rest := dataPaths(args)
	if len(rest) < 1 || len(rest) > 2 {
		fmt.Fprintln(os.Stderr, "usage: flexkb validate <layout-file> [variant]")
		fmt.Fprintln(os.Stderr, "  with no variant: report on every variant in the file")
		os.Exit(2)
	}
	root := makeRoot(paths)
	lf, err := root.LayoutFile(rest[0])
	check(err)

	var specs []model.LayoutSpec
	if len(rest) == 2 {
		for _, v := range lf.Variants {
			if v.Name == rest[1] {
				specs = append(specs, v)
				break
			}
		}
		if len(specs) == 0 {
			fmt.Fprintf(os.Stderr, "variant %q not found in %s\n", rest[1], rest[0])
			os.Exit(1)
		}
	} else {
		specs = lf.Variants
	}

	gaps := false
	for _, spec := range specs {
		reports, err := validate.ValidateVariant(root, lf, spec)
		if err != nil {
			fmt.Fprintf(os.Stderr, "%s/%s: %v\n", lf.File, spec.Name, err)
			os.Exit(1)
		}
		if len(reports) == 0 {
			fmt.Printf("%s(%s): no locale to validate against (skipped)\n", lf.File, spec.Name)
			continue
		}
		for _, r := range reports {
			fmt.Print(validate.FormatReport(r))
			if len(r.Missing) > 0 {
				gaps = true
			}
		}
	}
	if gaps {
		// Exit 1 so CI / scripts can gate on "all stacks complete".
		os.Exit(1)
	}
}

func runMigrateSuggest(args []string) {
	if len(args) < 2 {
		fmt.Fprintln(os.Stderr, "usage: flexkb migrate-suggest <layout-file> <variant-name>")
		os.Exit(2)
	}
	layout, variant := args[0], args[1]
	tokens := splitVariantTokens(variant)

	knownTrans := map[string]string{
		"qwerty": "qwerty", "qwertz": "qwertz", "azerty": "azerty",
		"dvorak": "dvorak", "colemak": "colemak", "workman": "workman",
		"norman": "norman", "bepo": "bepo",
		"f": "turkish-f", "ycuken": "ycuken",
	}
	knownAdds := map[string]string{
		"intl": "intl", "altgr-intl": "intl", "alt-intl": "intl",
		"deadkeys": "intl", "eurosign": "eurosign-e", "euro": "eurosign-5",
		"polish": "polish", "german": "german-umlauts",
		"spanish": "spanish", "portuguese": "portuguese",
		"french": "french-accents",
	}
	knownSubs := map[string]string{
		"phonetic": guessPhoneticSub(layout),
	}

	var trans string
	var adds []string
	var subs []string

	// Try to match multi-token addition names first (altgr-intl etc).
	joined := strings.Join(tokens, "-")
	for k, v := range knownAdds {
		if strings.Contains(joined, k) {
			adds = append(adds, v)
		}
	}

	for _, tok := range tokens {
		if t, ok := knownTrans[tok]; ok && trans == "" {
			trans = t
			continue
		}
		if s, ok := knownSubs[tok]; ok && s != "" {
			subs = append(subs, s)
			continue
		}
	}

	if trans == "" {
		trans = "qwerty"
	}

	physical := "iso"
	if layout == "us" || layout == "ca" || layout == "us-mac" {
		physical = "ansi"
	}

	fmt.Printf("# Suggested flexkb entry for %s/%s — drop into data/layouts/%s.yaml:\n",
		layout, variant, layout)
	fmt.Printf("- name: %s\n", variant)
	fmt.Printf("  description: %s (%s, migrated)\n", layoutDisplay(layout), variant)
	fmt.Printf("  physical: %s\n", physical)
	fmt.Printf("  transformation: %s\n", trans)
	if len(adds) > 0 {
		fmt.Printf("  additions: [%s]\n", strings.Join(adds, ", "))
	}
	if len(subs) > 0 {
		fmt.Printf("  substitutions: [%s]\n", strings.Join(subs, ", "))
	}
	fmt.Println()
	fmt.Println("# This is a best-guess match. Compose it (`flexkb compose " + layout + " " + variant + "`)")
	fmt.Println("# and diff against the upstream variant to see how close it lands.")
	fmt.Println("# If it doesn't, mark it `passthrough: true` instead for verbatim upstream.")
}

func splitVariantTokens(s string) []string {
	out := []string{}
	for _, part := range strings.FieldsFunc(s, func(r rune) bool {
		return r == '-' || r == '_'
	}) {
		out = append(out, strings.ToLower(part))
	}
	return out
}

// guessPhoneticSub picks the right Latin→X phonetic substitution based
// on the layout name. Defaults to nothing if the layout's script isn't
// modelled yet.
func guessPhoneticSub(layout string) string {
	switch layout {
	case "ru", "ua", "by", "kg":
		return "latin-cyrillic-phonetic"
	case "bg", "mk", "rs":
		return "latin-cyrillic-bg-phonetic"
	case "gr":
		return "latin-greek-phonetic"
	case "il":
		return "latin-hebrew-phonetic"
	case "ara", "ir", "sa":
		return "latin-arabic-phonetic"
	}
	return ""
}

func layoutDisplay(layout string) string {
	known := map[string]string{
		"us": "English (US)", "gb": "English (UK)", "de": "German",
		"fr": "French", "es": "Spanish", "pt": "Portuguese",
		"ru": "Russian", "ua": "Ukrainian", "bg": "Bulgarian",
		"gr": "Greek", "tr": "Turkish", "il": "Hebrew",
		"ara": "Arabic", "pl": "Polish",
	}
	if v, ok := known[layout]; ok {
		return v
	}
	return strings.ToUpper(layout)
}

// runDropinCheck verifies the built tree is a strict superset of upstream
// — the actual definition of "drop-in compatible". This is the property
// the PKGBUILD's check() function enforces, so a regression in the build
// pipeline fails the package build, not just an install-time warning.
func runDropinCheck(args []string) {
	if len(args) != 2 {
		fmt.Fprintln(os.Stderr, "usage: flexkb dropin-check <built-tree> <upstream-tree>")
		os.Exit(2)
	}
	report, err := dropincheck.Check(args[0], args[1])
	if err != nil {
		fmt.Fprintln(os.Stderr, "error:", err)
		os.Exit(2)
	}
	if report.IsClean() {
		fmt.Printf("OK: %s is a strict superset of %s\n", args[0], args[1])
		return
	}
	if len(report.MissingFiles) > 0 {
		fmt.Printf("FAIL: %d file(s) from upstream missing in built tree\n", len(report.MissingFiles))
		for _, m := range report.MissingFiles {
			fmt.Println("  ", m)
		}
	}
	if len(report.MissingVariants) > 0 {
		fmt.Printf("FAIL: %d xkb_symbols block(s) missing\n", len(report.MissingVariants))
		for _, m := range report.MissingVariants {
			fmt.Println("  ", m)
		}
	}
	if len(report.MissingRules) > 0 {
		fmt.Printf("FAIL: %d rules registry entry/entries missing\n", len(report.MissingRules))
		for _, m := range report.MissingRules {
			fmt.Println("  ", m)
		}
	}
	os.Exit(1)
}

func check(err error) {
	if err == nil {
		return
	}
	fmt.Fprintln(os.Stderr, "error:", err)
	os.Exit(1)
}
